package Vista;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class CalculadorBooleana extends javax.swing.JFrame {

    public CalculadorBooleana() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLguardar, jPguardar);
        CambiosColorBoton.configurarCambiosColor(jLborrarHistorial, jPborrarHistorial);
        CambiosColorBoton.configurarCambiosColor(jLnegacion, jPnegacion);
        CambiosColorBoton.configurarCambiosColor(jLconjuncion, jPconjuncion);
        CambiosColorBoton.configurarCambiosColor(jLdisyuncion, jPdisyuncion);
        CambiosColorBoton.configurarCambiosColor(jLparenAbierto, jPparenArbierto);
        CambiosColorBoton.configurarCambiosColor(jLparenCerrado, jPparenCerrado);
        CambiosColorBoton.configurarCambiosColor(jLvariableA, jPvariableA);
        CambiosColorBoton.configurarCambiosColor(jLvariableB, jPvariableB);
        CambiosColorBoton.configurarCambiosColor(jLvariableC, jPvariableC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jLsalir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPnegacion = new javax.swing.JPanel();
        jLnegacion = new javax.swing.JLabel();
        jPconjuncion = new javax.swing.JPanel();
        jLconjuncion = new javax.swing.JLabel();
        jPdisyuncion = new javax.swing.JPanel();
        jLdisyuncion = new javax.swing.JLabel();
        jPparenArbierto = new javax.swing.JPanel();
        jLparenAbierto = new javax.swing.JLabel();
        jPparenCerrado = new javax.swing.JPanel();
        jLparenCerrado = new javax.swing.JLabel();
        jPvariableA = new javax.swing.JPanel();
        jLvariableA = new javax.swing.JLabel();
        jPvariableB = new javax.swing.JPanel();
        jLvariableB = new javax.swing.JLabel();
        jPvariableC = new javax.swing.JPanel();
        jLvariableC = new javax.swing.JLabel();
        jPguardar = new javax.swing.JPanel();
        jLguardar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jThistorialBooleana = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPborrarHistorial = new javax.swing.JPanel();
        jLborrarHistorial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTpantallaBooleana = new javax.swing.JTextArea();
        jPguardar1 = new javax.swing.JPanel();
        jLguardar1 = new javax.swing.JLabel();
        jPguardar2 = new javax.swing.JPanel();
        jLborrarVariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));

        jLregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        jLsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salie.png"))); // NOI18N
        jLsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLregresar))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(jLregresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLsalir)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, 510));

        jPanel3.setBackground(new java.awt.Color(192, 178, 131));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA BOOLEANA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 50));

        jPnegacion.setBackground(new java.awt.Color(220, 208, 192));

        jLnegacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Negacion.png"))); // NOI18N
        jLnegacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLnegacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnegacionLayout = new javax.swing.GroupLayout(jPnegacion);
        jPnegacion.setLayout(jPnegacionLayout);
        jPnegacionLayout.setHorizontalGroup(
            jPnegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnegacion, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPnegacionLayout.setVerticalGroup(
            jPnegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLnegacion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPnegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 40));
        jPnegacion.getAccessibleContext().setAccessibleName("");

        jPconjuncion.setBackground(new java.awt.Color(220, 208, 192));

        jLconjuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLconjuncion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Conjuncion.png"))); // NOI18N
        jLconjuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLconjuncionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPconjuncionLayout = new javax.swing.GroupLayout(jPconjuncion);
        jPconjuncion.setLayout(jPconjuncionLayout);
        jPconjuncionLayout.setHorizontalGroup(
            jPconjuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPconjuncionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLconjuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPconjuncionLayout.setVerticalGroup(
            jPconjuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPconjuncionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLconjuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPconjuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jPdisyuncion.setBackground(new java.awt.Color(220, 208, 192));

        jLdisyuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLdisyuncion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Disyuncion.png"))); // NOI18N
        jLdisyuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLdisyuncionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPdisyuncionLayout = new javax.swing.GroupLayout(jPdisyuncion);
        jPdisyuncion.setLayout(jPdisyuncionLayout);
        jPdisyuncionLayout.setHorizontalGroup(
            jPdisyuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdisyuncionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLdisyuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPdisyuncionLayout.setVerticalGroup(
            jPdisyuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdisyuncionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLdisyuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPdisyuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jPparenArbierto.setBackground(new java.awt.Color(220, 208, 192));

        jLparenAbierto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLparenAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pare1.png"))); // NOI18N
        jLparenAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLparenAbiertoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPparenArbiertoLayout = new javax.swing.GroupLayout(jPparenArbierto);
        jPparenArbierto.setLayout(jPparenArbiertoLayout);
        jPparenArbiertoLayout.setHorizontalGroup(
            jPparenArbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPparenArbiertoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLparenAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPparenArbiertoLayout.setVerticalGroup(
            jPparenArbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPparenArbiertoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLparenAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPparenArbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jPparenCerrado.setBackground(new java.awt.Color(220, 208, 192));

        jLparenCerrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLparenCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pare2.png"))); // NOI18N
        jLparenCerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLparenCerradoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPparenCerradoLayout = new javax.swing.GroupLayout(jPparenCerrado);
        jPparenCerrado.setLayout(jPparenCerradoLayout);
        jPparenCerradoLayout.setHorizontalGroup(
            jPparenCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPparenCerradoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLparenCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPparenCerradoLayout.setVerticalGroup(
            jPparenCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPparenCerradoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLparenCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPparenCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jPvariableA.setBackground(new java.awt.Color(220, 208, 192));

        jLvariableA.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLvariableA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLvariableA.setText("A");
        jLvariableA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLvariableAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPvariableALayout = new javax.swing.GroupLayout(jPvariableA);
        jPvariableA.setLayout(jPvariableALayout);
        jPvariableALayout.setHorizontalGroup(
            jPvariableALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvariableALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLvariableA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPvariableALayout.setVerticalGroup(
            jPvariableALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvariableALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLvariableA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPvariableA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jPvariableB.setBackground(new java.awt.Color(220, 208, 192));

        jLvariableB.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLvariableB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLvariableB.setText("B");
        jLvariableB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLvariableBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPvariableBLayout = new javax.swing.GroupLayout(jPvariableB);
        jPvariableB.setLayout(jPvariableBLayout);
        jPvariableBLayout.setHorizontalGroup(
            jPvariableBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvariableBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLvariableB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPvariableBLayout.setVerticalGroup(
            jPvariableBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvariableBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLvariableB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPvariableB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jPvariableC.setBackground(new java.awt.Color(220, 208, 192));

        jLvariableC.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLvariableC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLvariableC.setText("C");
        jLvariableC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLvariableCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPvariableCLayout = new javax.swing.GroupLayout(jPvariableC);
        jPvariableC.setLayout(jPvariableCLayout);
        jPvariableCLayout.setHorizontalGroup(
            jPvariableCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvariableCLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLvariableC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPvariableCLayout.setVerticalGroup(
            jPvariableCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPvariableCLayout.createSequentialGroup()
                .addComponent(jLvariableC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPvariableC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, 40));

        jPguardar.setBackground(new java.awt.Color(220, 208, 192));

        jLguardar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLguardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLguardar.setText("GUARDAR");
        jLguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLguardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardarLayout = new javax.swing.GroupLayout(jPguardar);
        jPguardar.setLayout(jPguardarLayout);
        jPguardarLayout.setHorizontalGroup(
            jPguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPguardarLayout.createSequentialGroup()
                .addComponent(jLguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPguardarLayout.setVerticalGroup(
            jPguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 160, -1));

        jThistorialBooleana.setEditable(false);
        jThistorialBooleana.setBackground(new java.awt.Color(255, 255, 255));
        jThistorialBooleana.setColumns(20);
        jThistorialBooleana.setRows(5);
        jScrollPane2.setViewportView(jThistorialBooleana);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 110, 270, 310));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Historial:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jPborrarHistorial.setBackground(new java.awt.Color(220, 208, 192));

        jLborrarHistorial.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLborrarHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLborrarHistorial.setText("BORRAR HISTORIAL");
        jLborrarHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLborrarHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLborrarHistorialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPborrarHistorialLayout = new javax.swing.GroupLayout(jPborrarHistorial);
        jPborrarHistorial.setLayout(jPborrarHistorialLayout);
        jPborrarHistorialLayout.setHorizontalGroup(
            jPborrarHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPborrarHistorialLayout.createSequentialGroup()
                .addComponent(jLborrarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPborrarHistorialLayout.setVerticalGroup(
            jPborrarHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPborrarHistorialLayout.createSequentialGroup()
                .addComponent(jLborrarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPborrarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 200, 40));

        jTpantallaBooleana.setEditable(false);
        jTpantallaBooleana.setBackground(new java.awt.Color(255, 255, 255));
        jTpantallaBooleana.setColumns(20);
        jTpantallaBooleana.setRows(5);
        jScrollPane1.setViewportView(jTpantallaBooleana);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 520, 130));

        jPguardar1.setBackground(new java.awt.Color(220, 208, 192));

        jLguardar1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLguardar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLguardar1.setText("BORRAR");
        jLguardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLguardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLguardar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardar1Layout = new javax.swing.GroupLayout(jPguardar1);
        jPguardar1.setLayout(jPguardar1Layout);
        jPguardar1Layout.setHorizontalGroup(
            jPguardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLguardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPguardar1Layout.setVerticalGroup(
            jPguardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLguardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 150, -1));

        jPguardar2.setBackground(new java.awt.Color(220, 208, 192));

        jLborrarVariable.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLborrarVariable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLborrarVariable.setText("BORRAR UNA VARIABLE");
        jLborrarVariable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLborrarVariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLborrarVariableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPguardar2Layout = new javax.swing.GroupLayout(jPguardar2);
        jPguardar2.setLayout(jPguardar2Layout);
        jPguardar2Layout.setHorizontalGroup(
            jPguardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLborrarVariable, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        jPguardar2Layout.setVerticalGroup(
            jPguardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPguardar2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLborrarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPguardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        MenuPrincipal menuPrin = new MenuPrincipal();
        menuPrin.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsalirMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLsalirMouseClicked

    private void jLnegacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLnegacionMouseClicked
     jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "¬");
    }//GEN-LAST:event_jLnegacionMouseClicked

    private void jLborrarHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLborrarHistorialMouseClicked
       jThistorialBooleana.setText("");
    }//GEN-LAST:event_jLborrarHistorialMouseClicked

    private void jLconjuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLconjuncionMouseClicked
      jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "∧");
    }//GEN-LAST:event_jLconjuncionMouseClicked

    private void jLdisyuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLdisyuncionMouseClicked
     jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "∨");
    }//GEN-LAST:event_jLdisyuncionMouseClicked

    private void jLparenAbiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLparenAbiertoMouseClicked
     jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "(");  
    }//GEN-LAST:event_jLparenAbiertoMouseClicked

    private void jLparenCerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLparenCerradoMouseClicked
     jTpantallaBooleana.setText(jTpantallaBooleana.getText() + ")"); 
    }//GEN-LAST:event_jLparenCerradoMouseClicked

    private void jLvariableAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLvariableAMouseClicked
    jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "A"); 
    }//GEN-LAST:event_jLvariableAMouseClicked

    private void jLvariableBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLvariableBMouseClicked
     jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "B"); 
    }//GEN-LAST:event_jLvariableBMouseClicked

    private void jLvariableCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLvariableCMouseClicked
    jTpantallaBooleana.setText(jTpantallaBooleana.getText() + "C"); 
    }//GEN-LAST:event_jLvariableCMouseClicked

    private void jLguardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLguardar1MouseClicked
     jTpantallaBooleana.setText("");
    }//GEN-LAST:event_jLguardar1MouseClicked

    private void jLguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLguardarMouseClicked
    String texto = jTpantallaBooleana.getText(); // Obtener el texto de jTpantallaBooleana
    jThistorialBooleana.append(texto + "\n");      
    }//GEN-LAST:event_jLguardarMouseClicked

    private void jLborrarVariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLborrarVariableMouseClicked
    String texto = jTpantallaBooleana.getText(); 
    if (!texto.isEmpty()) { 
    String nuevoTexto = texto.substring(0, texto.length() - 1);
    jTpantallaBooleana.setText(nuevoTexto);
    }
    }//GEN-LAST:event_jLborrarVariableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadorBooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadorBooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadorBooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadorBooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadorBooleana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLborrarHistorial;
    private javax.swing.JLabel jLborrarVariable;
    private javax.swing.JLabel jLconjuncion;
    private javax.swing.JLabel jLdisyuncion;
    private javax.swing.JLabel jLguardar;
    private javax.swing.JLabel jLguardar1;
    private javax.swing.JLabel jLnegacion;
    private javax.swing.JLabel jLparenAbierto;
    private javax.swing.JLabel jLparenCerrado;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JLabel jLsalir;
    private javax.swing.JLabel jLvariableA;
    private javax.swing.JLabel jLvariableB;
    private javax.swing.JLabel jLvariableC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPborrarHistorial;
    private javax.swing.JPanel jPconjuncion;
    private javax.swing.JPanel jPdisyuncion;
    private javax.swing.JPanel jPguardar;
    private javax.swing.JPanel jPguardar1;
    private javax.swing.JPanel jPguardar2;
    private javax.swing.JPanel jPnegacion;
    private javax.swing.JPanel jPparenArbierto;
    private javax.swing.JPanel jPparenCerrado;
    private javax.swing.JPanel jPvariableA;
    private javax.swing.JPanel jPvariableB;
    private javax.swing.JPanel jPvariableC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jThistorialBooleana;
    private javax.swing.JTextArea jTpantallaBooleana;
    // End of variables declaration//GEN-END:variables
}
