package Vista;

public class MenuConversores extends javax.swing.JFrame {

    public MenuConversores() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLbinarioDecimal, jPbinarioDecimal);
        CambiosColorBoton.configurarCambiosColor(jLbinarioHexa, jPbinarioHexa);
        CambiosColorBoton.configurarCambiosColor(jLdecimalBinario, jPdecimalBinario);
        CambiosColorBoton.configurarCambiosColor(jLhexaBinario, jPhexaBinario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jLsalir = new javax.swing.JLabel();
        jPbinarioHexa = new javax.swing.JPanel();
        jLbinarioHexa = new javax.swing.JLabel();
        jPhexaBinario = new javax.swing.JPanel();
        jLhexaBinario = new javax.swing.JLabel();
        jPbinarioDecimal = new javax.swing.JPanel();
        jLbinarioDecimal = new javax.swing.JLabel();
        jPdecimalBinario = new javax.swing.JPanel();
        jLdecimalBinario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));

        jLregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        jLsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salie.png"))); // NOI18N
        jLsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLregresar))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(jLregresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLsalir)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 140, 500));

        jPbinarioHexa.setBackground(new java.awt.Color(220, 208, 192));

        jLbinarioHexa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLbinarioHexa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbinarioHexa.setText("BINARIO A HEXADECIMAL");
        jLbinarioHexa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbinarioHexa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbinarioHexaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbinarioHexaLayout = new javax.swing.GroupLayout(jPbinarioHexa);
        jPbinarioHexa.setLayout(jPbinarioHexaLayout);
        jPbinarioHexaLayout.setHorizontalGroup(
            jPbinarioHexaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbinarioHexaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbinarioHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPbinarioHexaLayout.setVerticalGroup(
            jPbinarioHexaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbinarioHexaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbinarioHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPbinarioHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jPhexaBinario.setBackground(new java.awt.Color(220, 208, 192));

        jLhexaBinario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLhexaBinario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhexaBinario.setText("HEXADECIMAL A BINARIO");
        jLhexaBinario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLhexaBinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLhexaBinarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPhexaBinarioLayout = new javax.swing.GroupLayout(jPhexaBinario);
        jPhexaBinario.setLayout(jPhexaBinarioLayout);
        jPhexaBinarioLayout.setHorizontalGroup(
            jPhexaBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhexaBinarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLhexaBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPhexaBinarioLayout.setVerticalGroup(
            jPhexaBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhexaBinarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLhexaBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPhexaBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jPbinarioDecimal.setBackground(new java.awt.Color(220, 208, 192));

        jLbinarioDecimal.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLbinarioDecimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbinarioDecimal.setText("BINARIO A DECIMAL");
        jLbinarioDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbinarioDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbinarioDecimalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPbinarioDecimalLayout = new javax.swing.GroupLayout(jPbinarioDecimal);
        jPbinarioDecimal.setLayout(jPbinarioDecimalLayout);
        jPbinarioDecimalLayout.setHorizontalGroup(
            jPbinarioDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbinarioDecimalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbinarioDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPbinarioDecimalLayout.setVerticalGroup(
            jPbinarioDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbinarioDecimalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbinarioDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPbinarioDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jPdecimalBinario.setBackground(new java.awt.Color(220, 208, 192));

        jLdecimalBinario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLdecimalBinario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLdecimalBinario.setText("DECIMAL A BINARIO");
        jLdecimalBinario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLdecimalBinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLdecimalBinarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPdecimalBinarioLayout = new javax.swing.GroupLayout(jPdecimalBinario);
        jPdecimalBinario.setLayout(jPdecimalBinarioLayout);
        jPdecimalBinarioLayout.setHorizontalGroup(
            jPdecimalBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdecimalBinarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLdecimalBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPdecimalBinarioLayout.setVerticalGroup(
            jPdecimalBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdecimalBinarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLdecimalBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPdecimalBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jPanel3.setBackground(new java.awt.Color(192, 178, 131));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ DE CONVERSORES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLdecimalBinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLdecimalBinarioMouseClicked
        
        DecimalBinario deciBi = new DecimalBinario();
        deciBi.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jLdecimalBinarioMouseClicked

    private void jLbinarioDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbinarioDecimalMouseClicked
        
        BinarioDecimal binDeci = new BinarioDecimal();
        binDeci.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLbinarioDecimalMouseClicked

    private void jLhexaBinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLhexaBinarioMouseClicked
        
        HexadecimalBinario hexaBin = new HexadecimalBinario();
        hexaBin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLhexaBinarioMouseClicked

    private void jLbinarioHexaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbinarioHexaMouseClicked
        
        BinarioHexadecimal binHexa = new BinarioHexadecimal();
        binHexa.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLbinarioHexaMouseClicked

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        MenuPrincipal menuprin = new MenuPrincipal();
        menuprin.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsalirMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConversores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConversores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConversores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConversores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConversores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbinarioDecimal;
    private javax.swing.JLabel jLbinarioHexa;
    private javax.swing.JLabel jLdecimalBinario;
    private javax.swing.JLabel jLhexaBinario;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JLabel jLsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPbinarioDecimal;
    private javax.swing.JPanel jPbinarioHexa;
    private javax.swing.JPanel jPdecimalBinario;
    private javax.swing.JPanel jPhexaBinario;
    // End of variables declaration//GEN-END:variables
}
